id: P004187
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:59:20.046626
source_metadata:
  id: bdr:W1AC55
  title: རྒྱན་འཇུག་གཉིས་དང་བསྟོད་ཆེན་བཞི།
  author: ''
  volumes:
    6be9f6e75fd94df992855315019686dc:
      image_group_id: I2PD18859
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
