id: I27F9AFE7
legacy_id: P004187
ocr_import_info:
  bdrc_scan_id: W1AC55
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T17:22:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:37:44.084670+00:00'
last_modified: 2022-08-31 02:38:05.972290
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC55
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC55
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱན་འཇུག་གཉིས་དང་བསྟོད་ཆེན་བཞི།
statistics:
  ocr_word_mean_confidence_index: 0.6992136475783517
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I2PD18859:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18859
      total_pages: 216
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18859.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.6992136475783517
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
